---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-east1-docker.pkg.dev/tw-rd-ca-ray-huang/my-backend-repository/benclass:3effcc0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: secret-volume
              mountPath: /app/config.json
              subPath: config.json   # 這裡直接把 config.json 挂載到 /app 目錄下，容器應用會讀取它
      volumes:
        - name: secret-volume
          secret:
            secretName: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  clusterIP: 34.118.224.5
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
